AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sustainable Travel Planner - Lambda Microservices

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 512
    Architectures: [x86_64]
    Environment:
      Variables:
        AWS_REGION: !Ref AWS::Region
        USE_DDB: "true"
        DDB_SESSIONS_TABLE: travel_sessions
        DDB_MEMORY_TABLE: travel_memory

Parameters:
  OpenAIKey:
    Type: String
    NoEcho: true
  ModelName:
    Type: String
    Default: gpt-4o

Resources:
  # ---------- DynamoDB ----------
  TravelSessions:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: travel_sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH

  TravelMemory:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: travel_memory
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH

  # ---------- HTTP API ----------
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['*']
        AllowHeaders: ['*']

  # ---------- Shared Services ----------
  SharedServicesFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: shared-services
      CodeUri: shared-services/
      Handler: main.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: travel_sessions
      Environment:
        Variables:
          DEBUG: "false"
          OPENAI_API_KEY: !Ref OpenAIKey
          DDB_TTL_DAYS: "2"
          DDB_SESSIONS_TABLE: travel_sessions
          DDB_MEMORY_TABLE: travel_memory
          USE_DDB: "true"
      Events:
        # Expose its routes too (optional but handy for direct calls)
        AnyRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /shared/{proxy+}

  # ---------- Intent/Requirements ----------
  IntentServiceFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: intent-requirements-service
      CodeUri: intent-requirements-service/
      Handler: main.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: travel_memory
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIKey
          OPENAI_MODEL_NAME: !Ref ModelName
          CREWAI_TRACING_ENABLED: "false"
          USE_DDB: "true"
          DDB_MEMORY_TABLE: travel_memory
      Events:
        AnyRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /intent/{proxy+}

  # ---------- API Gateway (Orchestrator) ----------
  ApiGatewayFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stp-api-gateway
      CodeUri: api-gateway/
      Handler: main.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !GetAtt SharedServicesFn.Arn
              - !GetAtt IntentServiceFn.Arn
      Environment:
        Variables:
          DOWNSTREAM_MODE: "LAMBDA"
          INTENT_SERVICE_LAMBDA: !Ref IntentServiceFn
          SHARED_SERVICES_LAMBDA: !Ref SharedServicesFn
          OPENAI_API_KEY: !Ref OpenAIKey
      Events:
        TravelPlan:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /travel/plan

Outputs:
  ApiBaseUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
