AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Travel Planner with Docker Container Images (solves 250MB layer limit)

Globals:
  Function:
    Timeout: 120
    MemorySize: 1024
    Architectures: [x86_64]
    Environment:
      Variables:
        USE_S3: "true"
        AWS_S3_ENDPOINT: !Ref AwsS3Endpoint

Parameters:
  OpenAIKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key for LLM calls
  ModelName:
    Type: String
    Default: gpt-4o-mini
    Description: OpenAI model to use
  StateBucketName:
    Type: String
    Description: S3 bucket for application state (must be globally unique)
  StateBasePrefix:
    Type: String
    Default: prod
    Description: Prefix for S3 keys (e.g., dev, staging, prod)
  AwsS3Endpoint:
    Type: String
    Default: ""
    Description: "S3 endpoint URL (leave empty for AWS)"

Resources:
  # S3 Bucket for state
  StateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref StateBucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveOldState
            Status: Enabled
            Transitions:
              - StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 1
          - Id: ExpireOldState
            Status: Enabled
            ExpirationInDays: 30

  # API Gateway (HTTP)
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['*']
        AllowHeaders: ['*']
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50

  # Shared Services - Docker Container
  SharedServicesFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: shared-services
      PackageType: Image
      MemorySize: 3008
      Timeout: 300
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref StateBucketName
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIKey
          S3_BUCKET_NAME: !Ref StateBucketName
          S3_BASE_PREFIX: !Ref StateBasePrefix
          AWS_S3_ENDPOINT: !Ref AwsS3Endpoint
          USE_S3: "true"
          GUARDRAILS_ENABLED: "true"
          GUARDRAILS_TIMEOUT: "20"
      Events:
        SharedRoutes:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /shared/{proxy+}
        SecurityRoutes:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /security/{proxy+}
        SessionRoutes:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /session/{proxy+}
      LoggingConfig:
        LogGroup: !Sub '/aws/lambda/${AWS::StackName}-shared-services'
        LogFormat: JSON
    Metadata:
      Dockerfile: Dockerfile.shared-services
      DockerContext: ./
      DockerTag: latest

  SharedServicesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-shared-services'
      RetentionInDays: 7

  # Intent Requirements Service - Docker Container
  IntentServiceFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: intent-requirements-service
      PackageType: Image
      MemorySize: 3008
      Timeout: 300
      EphemeralStorage:
        Size: 5120
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref StateBucketName
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIKey
          OPENAI_MODEL_NAME: !Ref ModelName
          S3_BUCKET_NAME: !Ref StateBucketName
          S3_BASE_PREFIX: !Ref StateBasePrefix
          S3_MEMORY_PREFIX: "requirements/"
          AWS_S3_ENDPOINT: !Ref AwsS3Endpoint
          USE_S3: "true"
          CREWAI_TELEMETRY_DISABLED: "1"
          MAX_TOKENS: "300"
      Events:
        IntentRoutes:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /intent/{proxy+}
      LoggingConfig:
        LogGroup: !Sub '/aws/lambda/${AWS::StackName}-intent-service'
        LogFormat: JSON
    Metadata:
      Dockerfile: Dockerfile.intent-service
      DockerContext: ./
      DockerTag: latest

  IntentServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-intent-service'
      RetentionInDays: 7

  # API Gateway Lambda - Docker Container
  ApiGatewayFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stp-api-gateway
      PackageType: Image
      MemorySize: 2048
      Timeout: 330
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !GetAtt SharedServicesFn.Arn
                - !GetAtt IntentServiceFn.Arn
        - S3CrudPolicy:
            BucketName: !Ref StateBucketName
      Environment:
        Variables:
          DOWNSTREAM_MODE: "LAMBDA"
          INTENT_SERVICE_LAMBDA: !Ref IntentServiceFn
          SHARED_SERVICES_LAMBDA: !Ref SharedServicesFn
          S3_BUCKET_NAME: !Ref StateBucketName
          S3_BASE_PREFIX: !Ref StateBasePrefix
          AWS_S3_ENDPOINT: !Ref AwsS3Endpoint
          USE_S3: "true"
      Events:
        TravelPlan:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /travel/plan
        SessionInfo:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /travel/session/{session_id}
        HealthCheck:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /health
      LoggingConfig:
        LogGroup: !Sub '/aws/lambda/${AWS::StackName}-api-gateway'
        LogFormat: JSON
    Metadata:
      Dockerfile: Dockerfile.api-gateway
      DockerContext: ./
      DockerTag: latest

  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-api-gateway'
      RetentionInDays: 7

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"