AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Travel Planner with Docker Container Images (OpenAI Guardrails)

Globals:
  Function:
    Timeout: 120
    MemorySize: 1024
    Architectures: [x86_64]
    Environment:
      Variables:
        USE_S3: "true"
        AWS_S3_ENDPOINT: !Ref AwsS3Endpoint

Parameters:
  OpenAIKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key for LLM calls
  ModelName:
    Type: String
    Default: gpt-4o
    Description: OpenAI model to use
  StateBucketName:
    Type: String
    Default: iss-travel-planner
    Description: S3 bucket for application state (must be globally unique)
  StateBasePrefix:
    Type: String
    Default: intent_agent
    Description: Prefix for S3 keys (e.g., dev, staging, prod)
  AwsS3Endpoint:
    Type: String
    Default: ""
    Description: "S3 endpoint URL (leave empty for AWS)"

Resources:
  # # S3 Bucket for state
  # StateBucket:
  #   Type: AWS::S3::Bucket
  #   DeletionPolicy: Retain
  #   UpdateReplacePolicy: Retain
  #   Properties:
  #     BucketName: iss-travel-planner 
  #     VersioningConfiguration:
  #       Status: Enabled
  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: true
  #       BlockPublicPolicy: true
  #       IgnorePublicAcls: true
  #       RestrictPublicBuckets: true
  #     LifecycleConfiguration:
  #       Rules:
  #         - Id: ArchiveOldState
  #           Status: Enabled
  #           Transitions:
  #             - StorageClass: INTELLIGENT_TIERING
  #               TransitionInDays: 1
  #         - Id: ExpireOldState
  #           Status: Enabled
  #           ExpirationInDays: 30

  # API Gateway (HTTP)
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: intent-agent-api-prod
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['*']
        AllowHeaders: ['*']
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50

  # Shared Services - Docker Container (with OpenAI Moderation)
  SharedServicesFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: shared-functions-prod
      PackageType: Image
      MemorySize: 1024  # Reduced from 3008 (OpenAI API is lighter)
      Timeout: 60       # Reduced from 300 (faster than NeMo)
      Policies:
        - S3CrudPolicy:
            BucketName: iss-travel-planner 
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIKey
          S3_BUCKET_NAME: iss-travel-planner 
          S3_BASE_PREFIX: !Ref StateBasePrefix
          AWS_S3_ENDPOINT: !Ref AwsS3Endpoint
          S3_SESSIONS_PREFIX: "sessions" 
          USE_S3: "true"
          GUARDRAILS_ENABLED: "true"
          GUARDRAILS_TIMEOUT: "10"
      Events:
        SharedRoutes:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /shared/{proxy+}
        SecurityRoutes:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /security/{proxy+}
        SessionRoutes:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /session/{proxy+}
      LoggingConfig:
        LogGroup: '/aws/lambda/shared-functions-prod' 
        LogFormat: JSON
    Metadata:
      Dockerfile: Dockerfile.shared-services
      DockerContext: ./
      DockerTag: latest

  SharedServicesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/lambda/shared-functions-prod' 
      RetentionInDays: 7

  # Intent Requirements Service - Docker Container
  IntentServiceFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: intent-requirements-prod 
      PackageType: Image
      MemorySize: 3008
      Timeout: 300
      EphemeralStorage:
        Size: 5120
      Policies:
        - S3CrudPolicy:
            BucketName: iss-travel-planner 
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIKey
          OPENAI_MODEL_NAME: !Ref ModelName
          S3_BUCKET_NAME: iss-travel-planner 
          S3_BASE_PREFIX: !Ref StateBasePrefix
          S3_MEMORY_PREFIX: "requirements/"
          AWS_S3_ENDPOINT: !Ref AwsS3Endpoint
          USE_S3: "true"
          CREWAI_TELEMETRY_DISABLED: "1"
          MAX_TOKENS: "700"
      Events:
        IntentRoutes:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /intent/{proxy+}
      LoggingConfig:
        LogGroup: '/aws/lambda/intent-requirements-prod'
        LogFormat: JSON
    Metadata:
      Dockerfile: Dockerfile.intent-service
      DockerContext: ./
      DockerTag: latest

  IntentServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/lambda/intent-requirements-prod'
      RetentionInDays: 7

  # API Gateway Lambda - Docker Container
  ApiGatewayFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stp-api-gateway-prod
      PackageType: Image
      MemorySize: 3008
      Timeout: 900
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !GetAtt SharedServicesFn.Arn
                - !GetAtt IntentServiceFn.Arn
                - "arn:aws:lambda:ap-southeast-1:641675857341:function:planner-agent-prod" 
        - S3CrudPolicy:
            BucketName: iss-travel-planner 
        - Statement:  
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource:
                - "arn:aws:s3:::iss-travel-planner/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource:
                - "arn:aws:s3:::iss-travel-planner"
      Environment:
        Variables:
          DOWNSTREAM_MODE: "LAMBDA"
          INTENT_SERVICE_LAMBDA: !Ref IntentServiceFn
          SHARED_SERVICES_LAMBDA: !Ref SharedServicesFn
          S3_BUCKET_NAME: iss-travel-planner 
          S3_BASE_PREFIX: !Ref StateBasePrefix
          AWS_S3_ENDPOINT: !Ref AwsS3Endpoint
          USE_S3: "true"
          RETRIEVAL_AGENT_URL: "https://29jxwf52gb.execute-api.ap-southeast-1.amazonaws.com/prod/research"
          RETRIEVAL_AGENT_API_KEY: "pYSqYcivG1504xjeQAskn2iyVS7fZ2Uj14lK1w8v" 
          PLANNER_AGENT_FUNCTION: "arn:aws:lambda:ap-southeast-1:641675857341:function:planner-agent-prod"
      Events:
        TravelPlan:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /travel/plan
        SessionInfo:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /travel/session/{session_id}
        HealthCheck:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /health
      LoggingConfig:
        LogGroup: '/aws/lambda/stp-api-gateway-prod'
        LogFormat: JSON
    Metadata:
      Dockerfile: Dockerfile.api-gateway
      DockerContext: ./
      DockerTag: latest

  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/lambda/stp-api-gateway-prod'
      RetentionInDays: 7

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"