AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Travel Planner with Isolated Dependencies

Globals:
  Function:
    Runtime: python3.11
    Architectures: [x86_64]
    Timeout: 120
    MemorySize: 1024
    Environment:
      Variables:
        USE_S3: "true"
        AWS_REGION: !Ref AWS::Region
        PYTHONPATH: /opt/python:/var/runtime:/var/task
        AWS_S3_ENDPOINT: !Ref AwsS3Endpoint   # used in local with LocalStack

Parameters:
  OpenAIKey:
    Type: String
    NoEcho: true
  ModelName:
    Type: String
    Default: gpt-4o-mini
  StateBucketName:
    Type: String
  StateBasePrefix:
    Type: String
    Default: prod
  AwsS3Endpoint:
    Type: String
    # IMPORTANT:
    # - Local (SAM): default is localstack hostname reachable by lambdas on docker network
    # - Prod: pass empty string "" via parameter override
    Default: http://localstack:4566

Resources:
  # Common dependencies layer
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common-dependencies
      ContentUri: layers/common/
      CompatibleRuntimes: [python3.11]
      RetentionPolicy: Retain

  # CrewAI layer (for intent service)
  CrewAILayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: crewai-dependencies
      ContentUri: layers/crewai/
      CompatibleRuntimes: [python3.11]
      RetentionPolicy: Retain

  # NeMo layer (for shared services)
  NeMoLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nemo-dependencies
      ContentUri: layers/nemo/
      CompatibleRuntimes: [python3.11]
      RetentionPolicy: Retain

  # S3 Bucket (Prod; in local you won't create this, you’ll point to LocalStack)
  StateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref StateBucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldState
            Status: Enabled
            ExpirationInDays: 7

  # API Gateway (HTTP)
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['*']
        AllowHeaders: ['*']
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50

  # Shared Services
  SharedServicesFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: shared-services
      CodeUri: shared-services/
      Handler: main.lambda_handler
      Layers: 
        - !Ref CommonLayer
        - !Ref NeMoLayer
      MemorySize: 2048
      Timeout: 180
      ReservedConcurrentExecutions: 10
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref StateBucketName
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIKey
          S3_BUCKET_NAME: !Ref StateBucketName
          S3_BASE_PREFIX: !Ref StateBasePrefix
          GUARDRAILS_ENABLED: "true"
          GUARDRAILS_TIMEOUT: "20"
      Events:
        SharedRoutes:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /shared/{proxy+}
        SecurityRoutes:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /security/{proxy+}
        SessionRoutes:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /session/{proxy+}

  # Intent Requirements Service
  IntentServiceFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: intent-requirements-service
      CodeUri: intent-requirements-service/
      Handler: main.lambda_handler
      Layers:
        - !Ref CommonLayer
        - !Ref CrewAILayer
      MemorySize: 3008
      Timeout: 300
      ReservedConcurrentExecutions: 10
      EphemeralStorage:
        Size: 2048
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref StateBucketName
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIKey
          OPENAI_MODEL_NAME: !Ref ModelName
          S3_BUCKET_NAME: !Ref StateBucketName
          S3_BASE_PREFIX: !Ref StateBasePrefix
          S3_MEMORY_PREFIX: "requirements/"
          CREWAI_TELEMETRY_DISABLED: "1"
          MAX_TOKENS: "300"
      Events:
        IntentRoutes:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: ANY
            Path: /intent/{proxy+}

  # API Gateway Lambda (front door)
  ApiGatewayFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stp-api-gateway
      CodeUri: api-gateway/
      Handler: main.lambda_handler
      Layers:
        - !Ref CommonLayer
      MemorySize: 1024
      Timeout: 330
      ReservedConcurrentExecutions: 20
      Policies:
        - LambdaInvokeFunction:
            FunctionName: !Ref SharedServicesFn
        - LambdaInvokeFunction:
            FunctionName: !Ref IntentServiceFn
      Environment:
        Variables:
          DOWNSTREAM_MODE: "LAMBDA"           # Prod default; local override uses HTTP
          INTENT_SERVICE_LAMBDA: !Ref IntentServiceFn
          SHARED_SERVICES_LAMBDA: !Ref SharedServicesFn
      Events:
        TravelPlan:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /travel/plan
        SessionInfo:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /travel/session/{session_id}
        HealthCheck:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /health

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
